[project]
name = "pinn-starlight-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "rawpy==0.27.0",
    "tqdm==4.66.5",
    "torch",
    "torchvision",
    "lightning>=2.6.5",
    "jsonargparse[signatures]>=4.50.0",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "tifffile>=2026.3.3",
    "segmentation-models-pytorch>=0.5.0",
    "scipy",
    "scipy-stubs",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/cu126"

